-- 코드를 입력하세요
SELECT TITLE, u.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') CREATED_DATE
from USED_GOODS_BOARD u, USED_GOODS_REPLY r
where u.CREATED_DATE between '2022-10-01' and '2022-10-31' and u.BOARD_ID = r.BOARD_ID
order by r.CREATED_DATE, u.title;